#!/bin/bash
#PBS -q hotel
#PBS -N related_individuals
#PBS -l nodes=1:ppn=16
#PBS -l walltime=24:00:00
#PBS -o /projects/ps-gymreklab/jmargoli/ukbiobank/sample_qc/snp_informed/hap/output
#PBS -e /projects/ps-gymreklab/jmargoli/ukbiobank/sample_qc/snp_informed/hap/output
#PBS -M jmargoli@ucsd.edu
#PBS -m a

source ~/.bashrc
conda activate python-igraph
python $UKB/sample_qc/snp_informed/hap/unrelated_individuals.py white_brit_high_quality_sane_kinship
conda deactivate

