__default__:
  # don't expect to modify
  account: ddp268
  partition: shared
  nodes: 1
  export: ALL
  mail-user: jbmargoliash@ucsd.edu
  # snakemake replaces {rule} and {wildcards}
  # https://snakemake.readthedocs.io/en/stable/snakefiles/configuration.html#cluster-configuration-deprecated
  # this is then passed to slurm, which replaces %j with jobid
  # https://support.pawsey.org.au/documentation/display/US/Customize+the+SLURM+output+file+name
  output: 'output/{rule}.{wildcards}.%j.out'
  # will modify for some tasks
  mem: 5G
  mail-type: FAIL
  # must set tasks-per-node, time and output for each task

load_shared_covars:
  tasks-per-node: 1
  time: '00:05:00'

decompress_phenotype:
  tasks-per-node: 1
  time: '05:00:00'

load_phenotype:
  tasks-per-node: 1
  time: '00:05:00'

plot_phenotype_by_sex:
  tasks-per-node: 5
  time: '24:00:00'

plot_phenotype_by_age:
  tasks-per-node: 5
  time: '24:00:00'
  mem: 30G

subset_samples_for_phenotype:
  tasks-per-node: 1
  time: '24:00:00'

rank_inverse_normalize_phenotype_subset:
  tasks-per-node: 1
  time: '00:05:00'

plot_str_locus:
  tasks-per-node: 1
  time: '00:30:00'

write_my_imputed_snp_gwas_readme:
  tasks-per-node: 1
  time: '00:05:00'

run_regional_my_imputed_snp_gwas:
  tasks-per-node: 1
  time: '12:00:00'
  mem: 9G

concatenate_my_imputed_snp_gwas_chr21:
  tasks-per-node: 1
  time: '04:00:00'

write_my_str_gwas_readme:
  tasks-per-node: 1
  time: '00:05:00'

run_regional_my_str_gwas:
  tasks-per-node: 1
  time: '12:00:00'
  mem: 9G

concatenate_my_str_gwas:
  tasks-per-node: 1
  time: '04:00:00'

prep_plink_input:
  tasks-per-node: 1
  time: '00:30:00'

timestamp_plink_run:
  tasks-per-node: 1
  time: '00:05:00'

run_plink_gwas:
  tasks-per-node: 28
  time: '23:30:00' # todo change back to 47
  mem: 110G

concatenate_plink_gwas:
  tasks-per-node: 1
  time: '04:00:00'

prep_conditional_input:
  tasks-per-node: 1
  time: '00:30:00'

run_conditional_my_str_gwas:
  tasks-per-node: 1
  time: '12:00:00'
  mem: 9G

prep_conditional_plink_input:
  tasks-per-node: 1
  time: '00:30:00'

run_conditional_plink_gwas:
  tasks-per-node: 28
  time: '23:30:00' # todo change back to 47
  mem: 110G
    
subset_my_gwas_results:
  tasks-per-node: 1
  time: '01:00:00'

subset_plink_gwas_results:
  tasks-per-node: 1
  time: '01:00:00'

subset_conditional_my_str_gwas_results:
  tasks-per-node: 1
  time: '01:00:00'

subset_conditional_plink_gwas_results:
  tasks-per-node: 1
  time: '01:00:00'

compare_my_to_plink_gwas:
  tasks-per-node: 1
  time: '00:30:00'
  mem: 50G

interactive_manhattan:
  tasks-per-node: 1
  time: '00:30:00'
  mem: 50G

interactive_manhattan_conditional:
  tasks-per-node: 1
  time: '00:30:00'
  mem: 50G

