#!/bin/bash
#PBS -q hotel
#PBS -N impute_STRs
#PBS -l nodes=1:ppn=4
#PBS -l walltime=00:30:00
#PBS -o /projects/ps-gymreklab/jmargoli/ukbiobank/str_imputed/hap_no_preqc/vcf_batches/output/
#PBS -e /projects/ps-gymreklab/jmargoli/ukbiobank/str_imputed/hap_no_preqc/vcf_batches/output/
#PBS -V
#PBS -M jmargoli@ucsd.edu
#PBS -m a
#INPUT1 beginning sample number (inclusive)
#INPUT2 end sample number (inclusive)
#INPUT3 chromosome number

#Make the inputs identifiable in the logs
echo INPUT1 $INPUT1 INPUT2 $INPUT2 INPUT3 $INPUT3
>&2 echo INPUT1 $INPUT1 INPUT2 $INPUT2 INPUT3 $INPUT3

cd /projects/ps-gymreklab/jmargoli/ukbiobank/str_imputed/hap_no_preqc
./cut_input_vcf.sh $INPUT1 $INPUT2 $INPUT3
./run_beagle.sh $INPUT1 $INPUT2 $INPUT3
