#!/bin/bash
#PBS -q hotel
#PBS -N mergeWithinChrRegion
#PBS -l nodes=1:ppn=1
#PBS -l walltime=48:00:00
#PBS -o /projects/ps-gymreklab/jmargoli/ukbiobank/str_imputed/hap_no_preqc/output/
#PBS -e /projects/ps-gymreklab/jmargoli/ukbiobank/str_imputed/hap_no_preqc/output/
#PBS -V
#PBS -M jmargoli@ucsd.edu
#PBS -m a

if [ -z "$INPUT1" ] ; then
        echo "didn't give INPUT1 argument - should be start position of chrom region"
        exit -1
fi

if [ -z "$INPUT2" ] ; then
        echo "didn't give INPUT2 argument - should be chrom number"
        exit -1
fi

#make the logs identifiable
echo INPUT1 $INPUT1 INPUT2 $INPUT2
>&2 echo INPUT1 $INPUT1 INPUT2 $INPUT2

END=$((INPUT1 + 9999999))

source ~/.bashrc
conda activate bcftools_custom
echo "Starting merge"
time bcftools merge $UKB/str_imputed/hap_no_preqc/vcf_batches/chr${INPUT2}_sample*.vcf.gz \
		    -o $UKB/str_imputed/hap_no_preqc/vcf_batches/chr${INPUT2}_pos_${INPUT1}_to_$END.vcf.gz -O z \
		    -r $INPUT2:$INPUT1-$END
conda deactivate
conda activate bcftools
echo "Done with merge, starting indexing"
time tabix -f $UKB/str_imputed/hap_no_preqc/vcf_batches/chr${INPUT2}_pos_${INPUT1}_to_$END.vcf.gz 
echo "Done with indexing"
conda deactivate
