#!/bin/bash
#PBS -q hotel
#PBS -N merge_VCFs
#PBS -l nodes=1:ppn=4
#PBS -l walltime=24:00:00
#PBS -o /projects/ps-gymreklab/jmargoli/ukbiobank/str_imputed/hap_no_preqc/output/
#PBS -e /projects/ps-gymreklab/jmargoli/ukbiobank/str_imputed/hap_no_preqc/output/
#PBS -V
#PBS -M jmargoli@ucsd.edu
#PBS -m a
#INPUT1 chromosome number

if [ -z "$INPUT1" ] ; then 
	echo "Didn't give INPUT1 argument - should be chormosome number"
	exit -1
fi

source ~/.bashrc
conda activate bcftools
time bcftools merge $UKB/str_imputed/hap_no_preqc/vcf_batches/*chr$INPUT1*.vcf.gz -o $UKB/str_imputed/hap_no_preqc/chr$INPUT1.vcf.gz --threads 4 -O z 
conda deactivate
