#!/bin/bash
#PBS -q hotel
#PBS -N merge_all
#PBS -l nodes=1:ppn=1
#PBS -l walltime=96:00:00
#PBS -o /projects/ps-gymreklab/jmargoli/ukbiobank/str_imputed/hap_no_preqc/output
#PBS -e /projects/ps-gymreklab/jmargoli/ukbiobank/str_imputed/hap_no_preqc/output
#PBS -V
#PBS -M jmargoli@ucsd.edu
#PBS -m a

if [ -z "$INPUT1" ] ; then
	echo "Didn't give INPUT1 argument - should be chrom number"
	exit -1
fi

source ~/.bashrc
conda activate ukb_analysis
time python $UKB/str_imputed/hap_no_preqc/merge_all.py $INPUT1
conda deactivate

