#!/bin/bash
#PBS -q hotel
#PBS -N validate
#PBS -l nodes=1:ppn=1
#PBS -l walltime=96:00:00
#PBS -o /projects/ps-gymreklab/jmargoli/ukbiobank/str_imputed/hap_no_preqc/output
#PBS -e /projects/ps-gymreklab/jmargoli/ukbiobank/str_imputed/hap_no_preqc/output
#PBS -V
#PBS -M jmargoli@ucsd.edu
#PBS -m a

if [ -z "$INPUT1" ] ; then
	echo "Didn't give INPUT1 argument - should be file to validate in tests folder"
	exit -1
fi

>&2 echo INPUT1 $INPUT1
echo INPUT1 $INPUT1

#confirm that my script produces valid VCFs
source ~/.bashrc
conda activate vcftools
time vcf-validator $UKB/str_imputed/hap_no_preqc/tests/$INPUT1
conda deactivate

