#!/bin/bash
#PBS -q hotel
#PBS -N check_for_period
#PBS -l nodes=1:ppn=1
#PBS -l walltime=24:00:00
#PBS -o /projects/ps-gymreklab/jmargoli/ukbiobank/association/output
#PBS -e /projects/ps-gymreklab/jmargoli/ukbiobank/association/output
#PBS -V
#PBS -M jmargoli@ucsd.edu
#PBS -m a

source "$HOME"/.bashrc
cd "$UKB/association" || { echo "Directory $UKB/association doesn't exist" ; exit 1 ; }
conda activate ukb
bcftools query \
	-f '%POS %INFO/PERIOD\n' \
	$UKB/str_imputed/runs/first_pass/vcfs/annotated_strs/chr$CHR.vcf.gz \
	> $UKB/temp/search_period_$CHR.txt
conda deactivate

