#!/bin/bash
#PBS -q hotel
#PBS -N merge_within_region_%CHROM%_%POS%
#PBS -l nodes=1:ppn=1
#PBS -l walltime=24:00:00
#PBS -o /projects/ps-gymreklab/jmargoli/ukbiobank/str_imputed/runs/%RUN_NAME%/batches/output/
#PBS -e /projects/ps-gymreklab/jmargoli/ukbiobank/str_imputed/runs/%RUN_NAME%/batches/output/
#PBS -V
#PBS -M jmargoli@ucsd.edu
#PBS -m a

#Note that this merge will spit out INFO fields from the first file in line.
#In particular, the AF and DR2 will be inaccurate.

run_name=%RUN_NAME%
chrom=%CHROM%
pos=%POS%

#make the logs identifiable
echo CHROM $chrom POS $pos RUN_NAME $run_name
>&2 echo CHROM $chrom POS $pos RUN_NAME $run_name

END=$((pos + 4999999))

source ~/.bashrc

conda activate ukb_analysis
files=$(python $UKB/str_imputed/scripts/list_batches_in_order.py $run_name $chrom)
conda deactivate

conda activate bcftools_custom
echo "Starting merge"
time bcftools merge $files \
		    -o $UKB/str_imputed/runs/$run_name/batches/chr${chrom}_pos_${pos}_to_${END}.vcf.gz -O z \
		    -r $chrom:$pos-$END
echo "Merge succeded"
conda deactivate

