#!/bin/bash
#PBS -q hotel
#PBS -N launch_gp_hardcall_filter
#PBS -l nodes=1:ppn=1
#PBS -l walltime=52:00:00
#PBS -o /projects/ps-gymreklab/jmargoli/ukbiobank/post_imputation_qc/output
#PBS -e /projects/ps-gymreklab/jmargoli/ukbiobank/post_imputation_qc/output
#PBS -V
#PBS -M jmargoli@ucsd.edu
#PBS -m a

source "$HOME"/.bashrc
cd "$UKB/post_imputation_qc" || { echo "Directory $UKB/exome doesn't exist" ; exit 1 ; }
conda activate ukb_analysis
python gp_harcall_filter.py
conda deactivate

