#!/bin/bash
#PBS -q condo
#PBS -N launch_fetch_10_bulk_fe_gvcfs
#PBS -l nodes=1:ppn=2
#PBS -l walltime=8:00:00
#PBS -o /projects/ps-gymreklab/jmargoli/ukbiobank/exome/fe_vcfs_output
#PBS -e /projects/ps-gymreklab/jmargoli/ukbiobank/exome/fe_vcfs_output
#PBS -V
#PBS -M jmargoli@ucsd.edu
#PBS -m a

source "$HOME"/.bashrc
cd "$UKB/exome" || { echo "Directory $UKB/exome doesn't exist" ; exit 1 ; }
conda activate ukb
python fetch_bulk_gvcfs.py fe fe_gvcfs.10.bulk
conda deactivate

