#!/bin/bash
#PBS -q home
#PBS -N launch_fetch_fe_plink
#PBS -l nodes=1:ppn=1
#PBS -l walltime=168:00:00
#PBS -o /projects/ps-gymreklab/jmargoli/ukbiobank/exome/fe_plink_output
#PBS -e /projects/ps-gymreklab/jmargoli/ukbiobank/exome/fe_plink_output
#PBS -V
#PBS -M jmargoli@ucsd.edu
#PBS -m a

source "$HOME"/.bashrc
cd "$UKB/exome/fe_plink" || { echo "Directory $UKB/exome doesn't exist" ; exit 1 ; }

# per instructions https://biobank.ndph.ox.ac.uk/showcase/field.cgi?id=23160
../../ukb_utilities/ukbgene efe -c1 \
	-a../../main_dataset/raw_data/k41414.key
../../ukb_utilities/ukbgene efe -c1 -m \
	-a../../main_dataset/raw_data/k41414.key
# per instructions https://biobank.ndph.ox.ac.uk/showcase/refer.cgi?id=1534
wget  -nd  biobank.ndph.ox.ac.uk/showcase/showcase/auxdata/ukb_fe_exm_chrall_v1.bim

