#!/bin/bash
#PBS -q home
#PBS -N launch_fetch_fe_crams
#PBS -l nodes=1:ppn=1
#PBS -l walltime=168:00:00
#PBS -o /projects/ps-gymreklab/jmargoli/ukbiobank/exome/fe_crams_output
#PBS -e /projects/ps-gymreklab/jmargoli/ukbiobank/exome/fe_crams_output
#PBS -V
#PBS -M jmargoli@ucsd.edu
#PBS -m a

source "$HOME"/.bashrc
cd "$UKB/exome" || { echo "Directory $UKB/exome doesn't exist" ; exit 1 ; }
conda activate ukb
python fetch_fe_crams.py
conda deactivate

