#!/bin/bash
#PBS -q hotel
#PBS -N grab_snpstr_panel_exome_calls
#PBS -l nodes=1:ppn=1
#PBS -l walltime=24:00:00
#PBS -e /projects/ps-gymreklab/jmargoli/ukbiobank/side_analyses/exome_strs/output
#PBS -o /projects/ps-gymreklab/jmargoli/ukbiobank/side_analyses/exome_strs/output
#PBS -V
#PBS -M jmargoli@ucsd.edu
#PBS -m a

if [ -z "$chr" ] ; then echo "chr variable is unset" ; exit 1 ; fi
source ~/.bashrc
conda activate ukb

bcftools query \
	-i ID=@"$UKB"/side_analyses/exome_strs/snpstr_exome_str_ids.txt \
	-f '%ID %REF %ALT [%GT:]\n' \
	"$UKB"/snpstr/1kg.snp.str.chr"${chr}".vcf.gz \
	> "$UKB"/side_analyses/exome_strs/snpstr_panel_exome_calls_hg19_chr"${chr}".txt
